on:
  workflow_call:
    inputs:
      plugin-path:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: CD to ${{ inputs.plugin-path }}
      run: cd ${{ inputs.plugin-path }}    
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Run tests  
      run: yarn test