name: Push to main on dai-deploy plugin

on:
  push:
    branches: [ "S-106199" ]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-deploy/**/README*'
      - 'plugins/dai-deploy/**/*.md'
      - 'plugins/dai-deploy-backend/**'  
      - 'plugins/dai-deploy-common/**'  

jobs:
  call-ci-workflow:
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy