name: Push to main on dai-deploy plugin

on:
  push:
    branches: [ "S-106202" ]  # need to map it to main branch
  #  paths-ignore:
      # Ignore changes to READMEs and other Markdown.
  #    - 'plugins/dai-deploy/**/README*'
  #    - 'plugins/dai-deploy/**/*.md'
  #    - 'plugins/dai-deploy-backend/**'
  #    - 'plugins/dai-deploy-common/**'

jobs:
  call-ci-workflow:
    if: |
      ${{
       contains(github.event_name, 'push') ||
       contains(toJson(github.event.commits.*.added), 'plugins/dai-deploy/**') ||
       contains(toJson(github.event.commits.*.modified), 'plugins/dai-deploy/**') ||
       }}
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy
      plugin: dai-deploy