name: Github Publish dai-deploy-common plugin

on: workflow_dispatch

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  github-publish:
    uses: ./.github/workflows/github-publish.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
