name: Push to main on dai-deploy-backend plugin

on:
  push:
    branches: [ "S-106202" ]  # need to map it to main branch
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-deploy-backend/**/README*'
      - 'plugins/dai-deploy-backend/**/*.md'
      - 'plugins/dai-deploy-backend/package.json'
      - 'plugins/dai-deploy/**'
      - 'plugins/dai-deploy-common/**'
      - '.github/**'

jobs:
  call-ci-workflow:
    name: Run build & test for dai-deploy-backend plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-backend
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy-backend
      plugin: dai-deploy-backend