name: Publish dai-deploy-common plugin

on: workflow_dispatch

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy-common
      plugin:  dai-deploy-common
      skip-tag: true
  github-publish:
    uses: ./.github/workflows/github-publish.yaml
    needs: [ version-tag ]
    with:
      plugin-path: ./plugins/dai-deploy-common
