name: Push to main on dai-deploy-common plugin

on:
  push:
    branches: [ "S-106202" ]  # need to map it to main branch

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      common: ${{ steps.changes.outputs.common }}
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            common:
              - 'plugins/dai-deploy-common/**'
            backend:
              - 'plugins/dai-deploy-backend/**'
            frontend:
              - 'plugins/dai-deploy/**'
          base: ${{ github.ref_name }}
  call-ci-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.common == 'true' }}
    name: Run build & test for dai-deploy-common plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy-common
      plugin: dai-deploy-common
  github-publish:
    needs: [ call-ci-workflow, version-tag ]
    uses: ./.github/workflows/github-publish.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  update-dependencies:
    needs: [ call-ci-workflow, version-tag, github-publish ]
    uses: ./.github/workflows/update-dependency.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
      plugin: dai-deploy-common

  frontend-call-ci-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' &&  needs.changes.outputs.common == 'false'}}
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy
  frontend-version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ frontend-call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy
      plugin: dai-deploy

  frontend1-call-ci-workflow:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' &&  needs.changes.outputs.common == 'true' && needs.update-dependencies.result == 'success' }}
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy
  frontend1-version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ frontend-call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy
      plugin: dai-deploy