name: Npm Publish dai-deploy-common plugin

on: workflow_dispatch

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  npm-publish:
    uses: ./.github/workflows/npm-publish.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
