name: Github Publish dai-deploy-common plugin

on:
  workflow_dispatch:
    github-publish:
      description: 'Npm publish'
      required: true
      default: true
      type: boolean
    npm-publish:
      description: 'Npm publish'
      required: true
      default: true
      type: boolean

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  github-publish:
    uses: ./.github/workflows/github-publish.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
  npm-publish:
    if: ${{ inputs.npm-publish == true }}
    uses: ./.github/workflows/npm-publish.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common

