name: Push to main on dai-deploy-backend plugin

on:
  push:
    branches: [ "S-106202" ]  # need to map it to main branch
  #  paths-ignore:
  #    # Ignore changes to READMEs and other Markdown.
  #    - 'plugins/dai-deploy-backend/**/README*'
  #    - 'plugins/dai-deploy-backend/**/*.md'
  #    - 'plugins/dai-deploy/**'
  #    - 'plugins/dai-deploy-common/**'

jobs:
  call-ci-workflow:
    if: github.event_name = 'push' && (contains(toJson(github.event.commits.*.added), 'plugins/dai-deploy-backend/**') ||  contains(toJson(github.event.commits.*.modified), 'plugins/dai-deploy-backend/**'))
    name: Run build & test for dai-deploy-backend plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-backend
  version-tag:
    uses: ./.github/workflows/version.yaml
    needs: [ call-ci-workflow ]
    with:
      plugin-path: ./plugins/dai-deploy-backend
      plugin: dai-deploy-backend