name: Pull requests for dai-deploy plugins

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/**/**/README*'
      - 'plugins/**/**/*.md'

jobs:
  dai-deploy-common-ci-workflow:
    name: Run build & test for dai-deploy-common plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-common
      local-links: true
  dai-deploy-backend-ci-workflow:    
    name: Run build & test for dai-deploy-backend plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy-backend  
      local-links: true
  dai-deploy-ci-workflow:    
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/reusable-build.yaml
    with:
      plugin-path: ./plugins/dai-deploy
      local-links: true