name: Build & test npm module

on:
  workflow_call:
    inputs:
      plugin-path:
        required: true
        type: string
      publish:
        required: false
        type: boolean

jobs:
  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Print Branch Name
        run: echo "Current branch is ${{ github.ref }}"
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: ${{ inputs.plugin-path }}
        with:
          commit-message: "CI: bumps version to {{version}} [skip ci]"
          major-wording: "MAJOR"
          minor-wording: "MINOR"
          patch-wording: "patch,fix"
          target-branch: ${{ github.ref }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ bump-version ]
    if: needs.bump-version.outputs.new-version != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessary to get newly created tag above
          ref: ${{ github.ref }}

      - name: New Version
        working-directory: ${{ inputs.plugin-path }}
        env:
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        run: echo "new version $NEW_VERSION"

      - name: Create tag and release
        uses: ncipollo/release-action@v1
        env:
          PACKAGEJSON_DIR: ${{ inputs.plugin-path }}
        with:
          commit: ${{ github.ref }}
          name: ${{ needs.bump-version.outputs.new-version }}
          tag: ${{ needs.bump-version.outputs.new-version }}


