# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Push to main on dai-deploy plugin

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      # Ignore changes to READMEs and other Markdown.
      - 'plugins/dai-deploy/**/README*'
      - 'plugins/dai-deploy/**/*.md'
      - 'plugins/dai-deploy-backend/**'  
      - 'plugins/dai-deploy-common/**'  

jobs:
  call-ci-workflow:
    name: Run build & test for dai-deploy plugin
    uses: ./.github/workflows/ci.yaml
    with:
      plugin-path: plugins/dai-deploy