name: Create GitHub Release

on:
  workflow_call:
    inputs:
      plugin-path:
        required: true
        type: string

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ bump-version ]
    if: needs.bump-version.outputs.new-version != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessary to get newly created tag above

      - name: New Version
        working-directory: ${{ inputs.plugin-path }}
        env:
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        run: echo "new version $NEW_VERSION"

      - name: Create tag and release
        uses: ncipollo/release-action@v1
        env:
          PACKAGEJSON_DIR: ${{ inputs.plugin-path }}
        with:
          name: ${{ needs.bump-version.outputs.new-version }}
          tag: ${{ needs.bump-version.outputs.new-version }}