name: Build & test npm module

on:
  workflow_call:
    inputs:
      plugin-path:
        required: true
        type: string
      publish:
        required: false
        type: boolean

jobs:
  build_job:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      working-directory: ${{ inputs.plugin-path }}
      run: yarn install
    - name: Run tsc
      working-directory: ${{ inputs.plugin-path }}
      run: yarn tsc
    - name: Build
      working-directory: ${{ inputs.plugin-path }}
      run: yarn build
    - name: Run tests  
      working-directory: ${{ inputs.plugin-path }}
      run: yarn test

  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}
    if: inputs.publish == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Wording ONLY looks at the commit message, not the PR title
      # Settings > pull requests > allow merge commits > default to pull request title
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        working-directory: ${{ inputs.plugin-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "CI: bumps version to {{version}} [skip ci]"
          major-wording: "MAJOR"
          minor-wording: "MINOR"
          target-branch: "main"

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ bump-version ]
    if: inputs.publish == true && needs.bump-version.outputs.new-version != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessary to get newly created tag above
          ref: 'main'

      - name: New Version
        working-directory: ${{ inputs.plugin-path }}
        env:
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        run: echo "new version $NEW_VERSION"

      - name: Create tag and release
        working-directory: ${{ inputs.plugin-path }}
        uses: ncipollo/release-action@v1
        with:
          commit: 'main'
          name: ${{ needs.bump-version.outputs.new-version }}
          tag: ${{ needs.bump-version.outputs.new-version }}

  # https://github.com/marketplace/actions/npm-publish
  github-publish:
    name: Publish Latest to Github registry
    runs-on: ubuntu-latest
    needs: [bump-version, create-release]
    if: inputs.publish == true && needs.bump-version.outputs.new-version != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessary to get newly created tag above
          ref: 'main'
      - name: Publish to registry
        if: ${{ inputs.publish }}
        working-directory: ${{ inputs.plugin-path }}
        run: yarn publish